#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:filetype=python
import time

def main():
    L = [2**(10),2**(20),2**(30)]
    for i in L:
        start = time.time()
        for counter in range(0,i+1,1):
            xor = counter / 4009
        end = time.time()
        print("Time to run %d is %1.10f" % (i,end-start))


if __name__=="__main__":
    main()
